projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - schema.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-1
        apiId: va3xqvw2yba3zabttc2ngxqeqm
        frontend: javascript
        framework: react
        maxDepth: 2
